name: Build frontend

on:
  push:
    branches:
      - master

env:
  REGISTRY: ghcr.io
  USERNAME: ${{ github.repository_owner }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up docker buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to ${{ env.REGISTRY }}
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ env.USERNAME }}
          password: ${{ secrets.CR_PAT }}

      - name: Generate short SHA
        id: sha
        run: echo "short_sha=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Build and push docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.USERNAME }}/${{ github.event.repository.name }}:${{ steps.sha.outputs.short_sha }}
          cache-from: type=gha
          cache-to: type=gha, mode=max